### ISSUE TITLE
RNSmtpMailer is null

### ISSUE THREAD

**Issue by r0adrunner** [angelos3lex/react-native-smtp-mailer#30] opened 2020-04-26 20:16 UTC
- Start a new expo bare project (v 3.18.6)
- $ npm install react-native-smtp-mailer --save
- follow manual installation (in android at least, the manual install is different than the automatic one)
- code: 
```
import RNSmtpMailer from "react-native-smtp-mailer";
console.log (RNSmtpMailer); // returns null
```
- run in android emulator

**Comment by angelos3lex** [comment] 2020-05-08 07:14
Hey @r0adrunner did you find any solution? Otherwise, i will have some time this Sunday to check it

**Comment by r0adrunner** [comment] 2020-05-10 01:26
Hi @angelos3lex 

Just realized the example I gave does not satisfy   
```
"peerDependencies": {
    "react-native": "^0.41.2"
  }
```
in package.json
Maybe it's that.
But didn't find any client solution, for the moment I'm going with a server solution.

But maybe a feature request, make it work with the latest react-native?

**Comment by JosMMV** [comment] 2020-05-14 23:06
I got this error message when import react-native-smtp-mailer:
`Could not find a declaration file for module 'react-native-smtp-mailer'. 'c:/Users/.../node_modules/react-native-smtp-mailer/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-native-smtp-mailer` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-smtp-mailer';` `

**Comment by Thanhcao86** [comment] 2020-06-04 11:29
ok. i found a solution is edit link this lib in Podfile.
`pod 'RNSmtpMailer', :path => '../node_modules/react-native-smtp-mailer/ios'`
instead of
`pod 'RNSmtpMailer', :path => '../node_modules/react-native-smtp-mailer`

It seems that the problem with the location of the podspec file path causes ios to be unable to get the link and unable to get resources

**Comment by angelos3lex** [comment] 2020-06-06 22:37
> 
> 
> I got this error message when import react-native-smtp-mailer:
> `Could not find a declaration file for module 'react-native-smtp-mailer'. 'c:/Users/.../node_modules/react-native-smtp-mailer/index.js' implicitly has an 'any' type. Try 'npm install @types/react-native-smtp-mailer' if it exists or add a new declaration (.d.ts) file containing 'declare module 'react-native-smtp-mailer';' `

This is because this module has no definition file yet. 


> 
> 
> ok. i found a solution is edit link this lib in Podfile.
> `pod 'RNSmtpMailer', :path => '../node_modules/react-native-smtp-mailer/ios'`
> instead of the original is
> `pod 'RNSmtpMailer', :path => '../node_modules/react-native-smtp-mailer`
> 
> It seems that the problem with the location of the podspec file path causes ios to be unable to get the link and unable to get resources

nice catch!

**Comment by r0adrunner** [comment] 2020-06-06 22:42
The bug report says it does not work in android emulator
The solutions posted by Thanhcao86 seem to be related to ios.
The problem posted by JosMMV seems unrelated to original error

Why is this closed?

**Comment by JosMMV** [comment] 2020-06-29 16:03
> The problem posted by JosMMV seems unrelated to original error

I got the original error too, but additionally, the console returns the error message that I posted.

**Comment by BepaTest** [comment] 2020-07-13 14:29
Hello,
I have the same issue working on Android emulator. I did automated linking and checked manual as well, but still have null.
Please help.

**Comment by angelos3lex** [comment] 2020-08-07 11:37
@r0adrunner This seems an issue after ejecting an expo project, as by using it in a new project initiated with react-native-cli on latest version works flawlessly.
Since i reproduced, the way i managed to resolve the issue was by the following steps:
 - npm i 
 - remove all manually linked steps, (autolink will do the work for u on next cmd)
 - react-native run-android
 - npm start
Then the imported module is no longer null. Not sure what helped. Probably the _npm i_ command, as the expo used yarn by default and as i can see there was a bad synchronization between them, making this module not visible for link, and the manual link was not working as well. It's not advised to use both in an app anyway, just one of them. Please close the issue if this fixes it for u

**Comment by BepaTest** [comment] 2020-08-11 08:08
@angelos3lex Thank you for your reply. My project wasn't expo at the beginning so I didn't do ejection. However react-native-smtp-mailer worked for me when I updated react-native version. Next step is to make attached pictures working :)

**Comment by angelos3lex** [comment] 2020-08-11 08:20
@BepaTest are you referring to [#29](https://github.com/angelos3lex/react-native-smtp-mailer/issues/29)?

**Comment by BepaTest** [comment] 2020-08-11 08:31
@angelos3lex 
#30 is resolved for me by updating react-native version
#29 will be my next step

**Closed** 2020-08-11 18:34 UTC
